### ISSUE TITLE
Nicht mit Datenpunkten aus 0_userdata kompatibel

### ISSUE THREAD

**Issue by DrBakterius** [ioBroker/ioBroker.vis-map#18]
Wenn ich für die Marker-Position einen Datenpunkt aus 0_userdata.0.*** auswähle, wird die Karte nicht geladen. Befindet sich derselbe Datenpunkt unter javascript.0.*** funktioniert es.

**Comment by Feuer-sturm** [comment]
Ist doppelt zu diesem issue https://github.com/ioBroker/ioBroker.vis-map/issues/10

**Comment by DrBakterius** [comment]
Danke. Schade, dass sich da in über 2 1/2 Jahren nichts getan hat... :-(
