### ISSUE TITLE
Anzeige Open Street Maps funktioniert nicht mehr

### ISSUE THREAD

**Issue by RK62** [ioBroker/ioBroker.vis-map#7]
Die Anzeige von Karten (Open Street Map) funktioniert nach und nach nicht mehr. Nach der Aktualisierung auf iOS 13 verweigert auch Safari auf dem iPad die Anzeige sowohl im Editor als auch bei der Anzeige via VIS:
- Mit Chrome funktioniert es
- Mit Internet Explorer, Edge und Safari wird nur noch ein "rosa Fenster" angezeigt

Edge bringt die folgende Fehlermeldung auf der Browserconsole:
`SEC7120: [CORS] Der Ursprung "http://10.0.0.210:38082" konnte "http://10.0.0.210:38082" im Access-Control-Allow-Origin response header für die cross-origin image-Ressource bei "http://b.tile.openstreetmap.org/14/8517/5498.png" nicht finden.
`
Gruß, Ralf

![image](https://user-images.githubusercontent.com/39200469/66713082-5d77d800-eda6-11e9-98c8-ce6c4f4520c3.png)

**Comment by 420Dope** [comment]
Habe auch das gleiche Problem.

**Comment by TA2k** [comment]
Sollte behoben sein mit der neusten Version

**Comment by RK62** [comment]
Wo finde ich denn „die neueste Version“?
Hier und im latest wird doch die 2 Jahre alte Version 1.0.2 angeboten die auch im Einsatz habe.

**Comment by TA2k** [comment]
Das dauert noch 1-2 Tage eh es im latest ist.
Wenn du es sofort haben willst. Auf der Adapter Seite auf das github icon klicken und dann auf beliebig von hier installieren:
https://github.com/TA2k/ioBroker.vis-map
Dann in instanzen vis neuladen und den browser cache leeren

**Comment by RK62** [comment]
Super, funktioniert unter iOS/Safari & Edge einwadfrei.
Danke!
